src/Entity/AdresseFacturation.php
<?php

namespace App\Entity;

use App\Repository\AdresseFacturationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdresseFacturationRepository::class)
 */
class AdresseFacturation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_rue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rue;

    /**
     * @ORM\Column(type="integer")
     */
    private $codepostal;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $pays;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $infocomplementaire;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="Adressefacturation")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $utilisateur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomPrenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $societe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $numTva;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function __toString()
    {
        return $this->getNom() . '[br]' . $this->getTelephone() . '[br]' . $this->getNumeroRue() . ' ' . $this->getRue() . '[br]' . $this->getCodepostal() . ' ' . $this->getVille() . '[br]' . $this->getPays();;
    }


    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNumeroRue(): ?int
    {
        return $this->numero_rue;
    }

    public function setNumeroRue(int $numero_rue): self
    {
        $this->numero_rue = $numero_rue;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getCodepostal(): ?int
    {
        return $this->codepostal;
    }

    public function setCodepostal(int $codepostal): self
    {
        $this->codepostal = $codepostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getInfocomplementaire(): ?string
    {
        return $this->infocomplementaire;
    }

    public function setInfocomplementaire(?string $infocomplementaire): self
    {
        $this->infocomplementaire = $infocomplementaire;

        return $this;
    }


    public function getUtilisateur(): ?Utilisateur
    {

        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nomPrenom;
    }

    public function setNomPrenom(string $nomPrenom): self
    {
        $this->nomPrenom = $nomPrenom;

        return $this;
    }

    public function getSociete(): ?string
    {
        return $this->societe;
    }

    public function setSociete(?string $societe): self
    {
        $this->societe = $societe;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(?string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getNumTva(): ?string
    {
        return $this->numTva;
    }

    public function setNumTva(?string $numTva): self
    {
        $this->numTva = $numTva;

        return $this;
    }
}

src/Form/AdresseFacturationType.php
<?php

namespace App\Form;

use App\Entity\AdresseFacturation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;

class AdresseFacturationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Quel nom souhaitez vous donner à votre adresse ?',
                'attr' => [
                    'placeholder' => 'Nommez votre adresse'
                ]
            ])
            ->add('nom_prenom', TextType::class, [
                'label' => 'Quel est votre nom et prenom ?',
                'attr' => [
                    'placeholder' => 'Saisissez votre nom et votre prenom'
                ]
            ])
            ->add('societe', TextType::class, [
                'label' => 'Votre societé',
                'required' => false,
                'attr' => [
                    'placeholder' => 'Facultatif',
                ]
            ])
            ->add('numero_rue', NumberType::class, [
                'label' => 'Quel est votre numéro de rue',
                'attr' => [
                    'placeholder' => 'Saisissez votre numéro de rue'
                ]

            ])
            ->add('telephone', TelType::class, [
                'label' => 'Votre numéro de telephone',
                'attr' => [
                    'placeholder' => 'Saisissez votre numero de telephone'
                ]
            ])
            ->add('rue', TextType::class, [
                'label' => 'Nom de rue',
                'attr' => ['placeholder' => 'Saisissez le numéro et le nom de rue']
            ])
            ->add('codepostal', NumberType::class, [
                'label' => 'Code postal',
                'attr' => ['placeholder' => 'Saisissez votre code postal']
            ])
            ->add('ville', TextType::class, [
                'label' => 'Ville',
                'attr' => ['placeholder' => 'Saisissez votre ville']
            ])

            ->add('pays', CountryType::class, [
                'label' => 'Pays',
                'attr' => [
                    'placeholder' => 'Votre pays'
                ]
            ])
            ->add('infocomplementaire', TextType::class, [
                'label' => 'Information complementaire',
                'attr' => ['placeholder' => 'Societé, batiment, interphone, code, etc.']
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Ajouter',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => AdresseFacturation::class,
        ]);
    }
}

src/Controller/AdresseFacturationController.php
<?php

namespace App\Controller;

use App\Entity\AdresseFacturation;
use App\Form\AdresseFacturationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\AdresseFacturationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/adresse-facturation")
 */
class AdresseFacturationController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/", name="app_adresse_facturation_index", methods={"GET"})
     */
    public function index(AdresseFacturationRepository $adresseFacturationRepository): Response
    {
        return $this->render('adresse_facturation/index.html.twig', [
            'adresse_facturations' => $adresseFacturationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_adresse_facturation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AdresseFacturationRepository $adresseFacturationRepository): Response
    {
        $adresseFacturation = new AdresseFacturation();
        $form = $this->createForm(AdresseFacturationType::class, $adresseFacturation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $adresseFacturation->setUtilisateur($this->getUser());


            $adresseFacturationRepository->add($adresseFacturation);
            $adresseFacturation->setUtilisateur($this->getUser());
            $this->entityManager->persist($adresseFacturation);

            $this->entityManager->flush();


            return $this->redirectToRoute('app_adresse_facturation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adresse_facturation/new.html.twig', [
            'adresse_facturation' => $adresseFacturation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_adresse_facturation_show", methods={"GET"})
     */
    public function show(AdresseFacturation $adresseFacturation): Response
    {
        return $this->render('adresse_facturation/show.html.twig', [
            'adresse_facturation' => $adresseFacturation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_adresse_facturation_edit", methods={"GET", "POST"})
     */
    public function edit($id, Request $request, AdresseFacturation $adresseFacturation, AdresseFacturationRepository $adresseFacturationRepository): Response
    {
        $addresse = $this->entityManager->getRepository(AdresseFacturation::class)->findOneById($id);

        if (!$addresse || $addresse->getUtilisateur()  != $this->getUser()) {
            return $this->redirectToRoute('index');
        }

        $form = $this->createForm(AdresseFacturationType::class, $adresseFacturation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $adresseFacturationRepository->add($adresseFacturation);
            return $this->redirectToRoute('app_adresse_facturation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adresse_facturation/edit.html.twig', [
            'adresse_facturation' => $adresseFacturation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_adresse_facturation_delete", methods={"POST"})
     */
    public function delete(Request $request, AdresseFacturation $adresseFacturation, AdresseFacturationRepository $adresseFacturationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $adresseFacturation->getId(), $request->request->get('_token'))) {
            $adresseFacturationRepository->remove($adresseFacturation);
        }

        return $this->redirectToRoute('app_adresse_facturation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/adresse_facturation/_delete_form.html.twig
<form method="post" action="{{ path('app_adresse_facturation_delete', {'id': adresse_facturation.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer cette adresse ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adresse_facturation.id) }}">
    <button class="btn btn-info">Supprimer cette adresse</button>
</form>

templates/adresse_facturation/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-6">{{ form_row(form.nom)}}</div>
    <div class="col-md-6">{{ form_row(form.nom_prenom)}}</div>
    <div class="col-md-6">{{ form_row(form.societe)}}</div>
    <div class="col-md-6">{{ form_row(form.numero_rue)}}</div>
    <div class="col-md-6">{{ form_row(form.rue)}}</div>
    <div class="col-md-6">{{ form_row(form.codepostal)}}</div>
    <div class="col-md-6">{{ form_row(form.ville)}}</div>
    <div class="col-md-6">{{ form_row(form.pays)}}</div>
    <div class="col-md-12">{{ form_row(form.infocomplementaire)}}</div>
</div>
{{ form_end(form) }}

templates/adresse_facturation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}The boutiq ! | Modifier votre Adresse de facturation{% endblock %}

{% block body %}
<div>
    <div>
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{path('mon_compte')}}" class="nav-links">Mon compte</a></li>
                <li class="breadcrumb-item"><a href="{{path('app_adresse_facturation_index')}}" class="nav-links">Mes adresses de facturation</a></li>
                <li class="breadcrumb-item current-page"> <a href="{{path('app_adresse_facturation_edit', {'id': adresse_facturation.id })}}" class="nav-links">Modifier adresse de facturation</a> </li>
            </ol>
        </nav>
    </div>
</div>
<div class=" my-formular container">
    <h1 class="text-center m-5">Modifier votre adresse de facturation</h1>

    {{ include('adresse_facturation/_form.html.twig', {'button_label': 'Appliquer'}) }}
</div>

{% endblock %}

templates/adresse_facturation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}The boutiq ! | Mes adresses de facturation{% endblock %}

{% block body %}
<div>
    <div>
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{path('mon_compte')}}" class="nav-links">Mon compte</a></li>
                <li class="breadcrumb-item current-page"> <a href="{{path('app_adresse_facturation_index')}}" class="nav-links">Mes adresses de facturation</a> </li>
            </ol>
        </nav>
    </div>
</div>
<div class="my-formular container">
    <h1 class="text-center m-3">Mes adresses de facturation</h1>
    {% if app.user.adresseFacturation is empty %}
    <p class="text-center"> Vous n'avez pas encore ajouté d'adresse de Facturation. Pour en ajouter une, veuillez
        <a href="{{path('app_adresse_facturation_new')}}">cliquer ici.</a>
    </p>
    {% else %}
    <div class="row">
        {% for adresse_facturation in app.user.adresseFacturation %}
        <div class="col-md-4">
            <div class="card" style="width: 20rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ adresse_facturation.nom }}</h5>
                    <p class="card-text">{{adresse_facturation.numeroRue}} - {{adresse_facturation.rue}} <br>
                        {{adresse_facturation.codepostal}} - {{adresse_facturation.ville}} <br>{{adresse_facturation.pays}}
                    </p>
                    <a class="btn btn-info" href="{{ path('app_adresse_facturation_show', {'id': adresse_facturation.id}) }}">Details</a>
                    <a class="btn btn-info" href="{{ path('app_adresse_facturation_edit', {'id': adresse_facturation.id}) }}">Modifier</a>

                    {{ include('adresse_facturation/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
        {% endfor %}

        {% endif %}
    </div>
    <a class="btn btn-info m-3" href="{{ path('app_adresse_facturation_new') }}">Créer une nouvelle adresse</a>
</div>
{% endblock %}

templates/adresse_facturation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}The boutiq ! | Nouvelle adresse de facturation{% endblock %}

{% block body %}
<div>
    <div>
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{path('index')}}" class="nav-links">Accueil</a></li>
                <li class="breadcrumb-item"> <a href="{{path('app_adresse_facturation_index')}}" class="nav-links">Mes adresses de facturation</a> </li>
                <li class="breadcrumb-item current-page"> <a href="{{path('index')}}" class="nav-links">Nouvelle adresse de facturation</a> </li>
            </ol>
        </nav>
    </div>
</div>
<div class="my-formular container">
    <h1 class="text-center m-5">Nouvelle adresse de facturation</h1>
    {{ include('adresse_facturation/_form.html.twig') }}
</div>
{% endblock %}

templates/adresse_facturation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AdresseFacturation{% endblock %}

{% block body %}
<div>
    <div>
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{path('mon_compte')}}" class="nav-links">Mon compte</a></li>
                <li class="breadcrumb-item current-page"> <a href="{{path('app_adresse_facturation_index')}}" class="nav-links">Mes adresses de facturation</a> </li>
                <li class="breadcrumb-item current-page"> <a href="{{path('app_adresse_facturation_show', {'id': adresse_facturation.id})}}" class="nav-links">Mon adresse de facturation</a> </li>
            </ol>
        </nav>
    </div>
</div>
<div class="my-formular example-wrapper">
    <h1 class="text-center">Votre adresse de facturation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ adresse_facturation.nom }}</td>
            </tr>
            <tr>
                <th>Numero de rue</th>
                <td>{{ adresse_facturation.numeroRue }}</td>
            </tr>
            <tr>
                <th>Rue</th>
                <td>{{ adresse_facturation.rue }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ adresse_facturation.codepostal }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ adresse_facturation.ville }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ adresse_facturation.pays }}</td>
            </tr>
            <tr>
                <th>Information complementaire</th>
                <td>{{ adresse_facturation.infocomplementaire }}</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex">

        <a href="{{ path('app_adresse_facturation_edit', {'id': adresse_facturation.id}) }}" class="btn btn-info m-2">Modifier</a>

        {{ include('adresse_facturation/_delete_form.html.twig') }}
    </div>
</div>

{% endblock %}